WebApplication1/Models/Classes/Despesa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebApplication1.Models.Validator;

namespace WebApplication1.Models.Classes
{
    public class Despesa : IValidatableObject
    {
        public int Id { get; set; }
        [Display(Name = "Nome da Despesa")]
        public String NomeDespesa { get; set; }
        [DisplayFormat(DataFormatString = "{0:c2}", ApplyFormatInEditMode = true)]
        public float Valor { get; set; }
        [Display(Name = "Tipo da Despesa")]
        public TipoDespesa TipoDespesa { get; set; }
        public int IdTipoDespesa { get; set; }
        public EnumCaracteristicaDespesa CaractDespesa { get; set; }
        [Display(Name = "Data de Realização")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DataRealizacao { get; set; }

        public Parcelamento Parcelamento { get; set; }
        public int NumeroParcelas { get; set; }
        [Display(Name = "Primeiro Vencimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime VencimentoPrimeiraParcela { get; set; }

        public Boolean Ofx { get; set; }

        public Conta conta { get; set; }
        public int IDConta { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var validator = new DespesaValidator();
            var result = validator.Validate(this);
            return result.Errors.Select(erro => new ValidationResult(erro.ErrorMessage, new[] { erro.PropertyName }));
        }
    }
}

WebApplication1/Controllers/DespesasController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.Classes;

namespace WebApplication1.Controllers
{
    public class DespesasController : Controller
    {
        private WebApplication1Context db = new WebApplication1Context();

        // GET: Despesas
        public ActionResult Index(String buscar, String buscarIni, String buscarFim, String Tipo)
        {
            DateTime date1, date2;
            if (String.IsNullOrEmpty(buscarIni) && String.IsNullOrEmpty(buscar) && String.IsNullOrEmpty(buscarFim) && (String.IsNullOrEmpty(Tipo) || Tipo.Equals("Todas")))
            {
                return View(db.Despesas.Include(db => db.TipoDespesa).ToList());
            }
            if (String.IsNullOrEmpty(buscarIni))
            {
                date1 = new DateTime(0001, 01, 01);
            }
            else
            {
                date1 = DateTime.Parse(buscarIni);
            }
            if (String.IsNullOrEmpty(buscarFim))
            {
                date2 = DateTime.Today;
            }
            else
            {
                date2 = DateTime.Parse(buscarFim);
            }

            var result = db.Despesas.Include(db => db.TipoDespesa).Where(x => x.DataRealizacao.CompareTo(date1) >= 0 && x.DataRealizacao.CompareTo(date2) < 0 && x.TipoDespesa.Nome.ToLower().Contains(buscar));
            if (Tipo.Equals("Ofx"))
            {
                result = result.Where(x => x.Ofx == true);
            }


            return View(result.ToList());
        }

        // GET: Despesas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesa despesa = db.Despesas.Find(id);
            if (despesa == null)
            {
                return HttpNotFound();
            }
            return View(despesa);
        }

        // GET: Despesas/Create
        public ActionResult Create()
        {
            ArrayList lista = new ArrayList();
            for (int i = 1; i < 7; i++)
            {
                lista.Add(i);
            }
            ViewBag.NumParcelas = new SelectList(lista);
            ViewBag.IdTipoDespesa = new SelectList(db.TipoDespesas, "Id", "Nome");
            return View();
        }

        // POST: Despesas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NomeDespesa,Valor,IdTipoDespesa,CaractDespesa,DataRealizacao,Parcelamento,NumeroParcelas,VencimentoPrimeiraParcela")] Despesa despesa, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                despesa.NumeroParcelas = int.Parse(form["NumParcelas"]);

                despesa.Ofx = false;
                db.Despesas.Add(despesa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ArrayList lista = new ArrayList();
            for (int i = 1; i < 7; i++)
            {
                lista.Add(i);
            }
            ViewBag.NumParcelas = new SelectList(lista, despesa.NumeroParcelas);
            ViewBag.IdTipoDespesa = new SelectList(db.TipoDespesas, "Id", "Nome", despesa.IdTipoDespesa);
            return View(despesa);
        }

        // GET: Despesas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesa despesa = db.Despesas.Find(id);
            if (despesa == null)
            {
                return HttpNotFound();
            }
            ArrayList lista = new ArrayList();
            for (int i = 1; i < 7; i++)
            {
                lista.Add(i);
            }
            ViewBag.NumParcelas = new SelectList(lista, despesa.NumeroParcelas);
            ViewBag.IdTipoDespesa = new SelectList(db.TipoDespesas, "Id", "Nome", despesa.IdTipoDespesa);
            return View(despesa);
        }

        // POST: Despesas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NomeDespesa,Valor,IdTipoDespesa,CaractDespesa,DataRealizacao,Parcelamento,NumeroParcelas,VencimentoPrimeiraParcela")] Despesa despesa, FormCollection form)
        {
            if (ModelState.IsValid)
            {
                despesa.NumeroParcelas = int.Parse(form["NumParcelas"]);
                db.Entry(despesa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ArrayList lista = new ArrayList();
            for (int i = 1; i < 7; i++)
            {
                lista.Add(i);
            }
            ViewBag.NumParcelas = new SelectList(lista, despesa.NumeroParcelas);
            ViewBag.IdTipoDespesa = new SelectList(db.TipoDespesas, "Id", "Nome", despesa.IdTipoDespesa);
            return View(despesa);
        }

        // GET: Despesas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Despesa despesa = db.Despesas.Find(id);
            if (despesa == null)
            {
                return HttpNotFound();
            }
            return View(despesa);
        }

        // POST: Despesas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Despesa despesa = db.Despesas.Find(id);
            db.Despesas.Remove(despesa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Despesas/Create.cshtml
@model WebApplication1.Models.Classes.Despesa

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Despesa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeDespesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeDespesa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeDespesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDespesa, "IdTipoDespesa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDespesa", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDespesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaractDespesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.CaractDespesa, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CaractDespesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataRealizacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataRealizacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataRealizacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parcelamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Parcelamento, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Parcelamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroParcelas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NumParcelas", null, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NumeroParcelas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VencimentoPrimeiraParcela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VencimentoPrimeiraParcela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VencimentoPrimeiraParcela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Despesas/Delete.cshtml
@model WebApplication1.Models.Classes.Despesa

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Despesa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoDespesa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDespesa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeDespesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDespesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaractDespesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaractDespesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataRealizacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataRealizacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parcelamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parcelamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroParcelas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroParcelas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VencimentoPrimeiraParcela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VencimentoPrimeiraParcela)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Despesas/Details.cshtml
@model WebApplication1.Models.Classes.Despesa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Despesa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoDespesa.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDespesa.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeDespesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeDespesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CaractDespesa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CaractDespesa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataRealizacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataRealizacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parcelamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parcelamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroParcelas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroParcelas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VencimentoPrimeiraParcela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VencimentoPrimeiraParcela)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Despesas/Edit.cshtml
@model WebApplication1.Models.Classes.Despesa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Despesa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeDespesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeDespesa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeDespesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDespesa, "IdTipoDespesa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDespesa", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDespesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaractDespesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.CaractDespesa, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CaractDespesa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataRealizacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataRealizacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataRealizacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parcelamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Parcelamento, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Parcelamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroParcelas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NumParcelas", null, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NumeroParcelas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VencimentoPrimeiraParcela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VencimentoPrimeiraParcela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VencimentoPrimeiraParcela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Views/Despesas/Index.cshtml
@model IEnumerable<WebApplication1.Models.Classes.Despesa>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form asp-controller="Despesas" asp-action="Index" method="get">
    <p>
        Pesquisar por tipo: @Html.TextBox("buscar")
    </p>
    <p>
        Data de início: @Html.TextBox("buscarIni")
        Data de fim: @Html.TextBox("buscarFim")
    </p>
    @Html.RadioButton("Tipo", "Todas", true) Todas
    @Html.RadioButton("Tipo", "Ofx") Somente Importadas
    <input type="submit" value="Pesquisar" />
    </p>
</form>

<table class="table">
    <tr>
        <th>
            Tipo
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeDespesa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CaractDespesa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataRealizacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Parcelamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroParcelas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VencimentoPrimeiraParcela)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TipoDespesa.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeDespesa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaractDespesa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataRealizacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parcelamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroParcelas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VencimentoPrimeiraParcela)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
    <tfoot class="footer">
        <tr>
            <td colspan="2"><b>Total</b></td>
            <td colspan="6">@Html.Raw(String.Format("<b>R$ {0:n2}</b>", @Model.Sum(i => i.Valor)))</td>
        </tr>
    </tfoot>
</table>